#! /bin/sh
D=`dirname $0`
DIR=`cd $D; pwd`
script=$DIR/lmc.rb

if test "x$1" = "x-d"; then
  irb -r $script
else
  if test "x$DEBUG" = "x1"; then
    gdb -ex run --args ruby $script
  else
    ruby $script
  fi
fi
