#! /bin/sh

./configure && make -C src clean && make -C src && \
  (cd src/ruby-binding; ruby extconf.rb) && \
  make -C src/ruby-binding/ && \
  (cd src/tests; ruby extconf.rb) && \
  make -C src/tests/ && ./src/tests/lmc 
