#! /bin/sh
D=`dirname $0`
DIR=`cd $D; pwd`
script=$DIR/ttalloc.rb

if test "x$1" = "x-d"; then
  irb -r $script
else
  time ruby $script 
  #valgrind --leak-check=full --tool=memcheck ruby $script
fi
